[package]
name = "utf8-io"
version = "0.3.1-alpha.0"
description = "Traits and types for UTF-8 I/O"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["stream", "text"]
categories = ["os", "text-processing"]
repository = "https://github.com/sunfishcode/utf8-io"
edition = "2018"
readme = "README.md"

[build-dependencies]
rustc_version = "0.3.2"

[dependencies]
duplex = "0.1.0"
layered-io = { version = "0.3.0", optional = true }
terminal-io = { version = "0.2.0", optional = true }
unsafe-io = "0.5.0"

[dev-dependencies]
anyhow = "1.0.37"
layered-io = "0.3.0"

[badges]
maintenance = { status = "actively-developed" }
